import { PIDDefinition } from '../shared/types';

// ─── SAE J1979 Formula helpers ─────────────────────────────────────────────────

const pct1   = (b: number[]) => parseFloat(((b[0] / 255) * 100).toFixed(1));
const pct2   = (b: number[]) => parseFloat((((b[0] * 256 + b[1]) / 65535) * 100).toFixed(1));
const trim   = (b: number[]) => parseFloat((((b[0] - 128) / 128) * 100).toFixed(1));
const tempC  = (b: number[]) => b[0] - 40;
const tempF  = (b: number[]) => parseFloat(((b[0] - 40) * 9 / 5 + 32).toFixed(1));
const rpm    = (b: number[]) => parseFloat(((b[0] * 256 + b[1]) / 4).toFixed(0));
const speed  = (b: number[]) => b[0];  // km/h
const kpa1   = (b: number[]) => b[0];  // kPa direct
const psi1   = (b: number[]) => parseFloat((b[0] * 0.14504).toFixed(1));
const volt1  = (b: number[]) => parseFloat(((b[0] * 256 + b[1]) / 1000).toFixed(3));
const maf    = (b: number[]) => parseFloat(((b[0] * 256 + b[1]) / 100).toFixed(2));
const timing = (b: number[]) => parseFloat(((b[0] / 2) - 64).toFixed(1));
const o2v    = (b: number[]) => parseFloat((b[0] / 200).toFixed(3));
const lph    = (b: number[]) => parseFloat(((b[0] * 256 + b[1]) / 20).toFixed(2));

// ─── PID Catalog ──────────────────────────────────────────────────────────────

export const PID_CATALOG: PIDDefinition[] = [

  // ── Engine ──────────────────────────────────────────────────────────────────
  {
    pid: '010C',
    name: 'Engine Crankshaft Speed',
    shortName: 'Engine RPM',
    category: 'engine',
    unit: 'rpm',
    min: 0,
    max: 8000,
    formula: '((byte A × 256) + byte B) ÷ 4',
    description: 'Crankshaft rotation speed. Core timing reference for all Engine Control Module calculations. The 5.3 L Vortec V8 redlines at 6,000 rpm.',
    decode: rpm,
    format: (v) => `${v} rpm`,
    warnHigh: 5500,
    critHigh: 6000,
  },
  {
    pid: '010D',
    name: 'Vehicle Road Speed',
    shortName: 'Speed',
    category: 'engine',
    unit: 'km/h',
    min: 0,
    max: 255,
    formula: 'byte A (km/h direct)',
    description: 'Wheel speed from the Vehicle Speed Sensor on the transmission output shaft.',
    decode: speed,
    format: (v) => `${v} km/h`,
  },
  {
    pid: '0104',
    name: 'Calculated Engine Load',
    shortName: 'Eng Load',
    category: 'engine',
    unit: '%',
    min: 0,
    max: 100,
    formula: '(byte A ÷ 255) × 100',
    description: 'Ratio of current air intake to maximum possible at this engine speed. Shows how hard the engine is working.',
    decode: pct1,
    format: (v) => `${v}%`,
    warnHigh: 85,
  },
  {
    pid: '0111',
    name: 'Throttle Plate Opening Position',
    shortName: 'Throttle',
    category: 'engine',
    unit: '%',
    min: 0,
    max: 100,
    formula: '(byte A ÷ 255) × 100',
    description: 'Throttle body butterfly plate angle measured by the Throttle Position Sensor. 0% = fully closed; 100% = wide-open throttle.',
    decode: pct1,
    format: (v) => `${v}%`,
  },
  {
    pid: '0145',
    name: 'Relative Throttle Position',
    shortName: 'Rel Throttle',
    category: 'engine',
    unit: '%',
    min: 0,
    max: 100,
    formula: '(byte A ÷ 255) × 100',
    description: 'Throttle position relative to the Engine Control Module\'s learned closed-position stop. More accurate than 0111 at idle.',
    decode: pct1,
    format: (v) => `${v}%`,
  },
  {
    pid: '0121',
    name: 'Redundant Throttle Position (Sensor B)',
    shortName: 'TPS-B',
    category: 'engine',
    unit: '%',
    min: 0,
    max: 100,
    formula: '(byte A ÷ 255) × 100',
    description: 'Second Throttle Position Sensor for redundancy. A large difference from parameter 0111 indicates a sensor fault.',
    decode: pct1,
    format: (v) => `${v}%`,
  },
  {
    pid: '010E',
    name: 'Ignition Timing Advance — Cylinder 1 Reference',
    shortName: 'Timing Adv',
    category: 'engine',
    unit: '° BTDC',
    min: -64,
    max: 63.5,
    formula: '(byte A ÷ 2) − 64',
    description: 'Degrees before top dead center at which the spark fires. The Engine Control Module retards timing on knock detection.',
    decode: timing,
    format: (v) => `${v}° BTDC`,
    warnLow: 0,
  },
  {
    pid: '0110',
    name: 'Mass Air Flow Rate',
    shortName: 'MAF',
    category: 'engine',
    unit: 'g/s',
    min: 0,
    max: 655.35,
    formula: '((byte A × 256) + byte B) ÷ 100',
    description: 'Mass of air entering the intake per second via the hot-wire Mass Air Flow sensor. Core Engine Control Module input for fuel injection calculation.',
    decode: maf,
    format: (v) => `${v} g/s`,
  },
  {
    pid: '010B',
    name: 'Intake Manifold Absolute Pressure',
    shortName: 'MAP',
    category: 'engine',
    unit: 'psi',
    min: 0,
    max: 36.75,
    formula: 'byte A × 0.14504 (kilopascal to psi)',
    description: 'Absolute pressure inside the intake manifold. Low at idle due to vacuum; rises toward atmospheric at wide-open throttle.',
    decode: psi1,
    format: (v) => `${v} psi`,
  },
  {
    pid: '0143',
    name: 'Absolute Throttle Body Air Intake Load',
    shortName: 'Abs Load',
    category: 'engine',
    unit: '%',
    min: 0,
    max: 100,
    formula: '((byte A × 256) + byte B) ÷ 2.55',
    description: 'Absolute percentage of maximum possible air intake at current conditions, independent of engine speed.',
    decode: pct2,
    format: (v) => `${v}%`,
  },

  // ── Temperature ──────────────────────────────────────────────────────────────
  {
    pid: '0105',
    name: 'Engine Coolant Temperature',
    shortName: 'Coolant Temp',
    category: 'temperature',
    unit: '°F',
    min: -40,
    max: 419,
    formula: '(byte A − 40) × 9 ÷ 5 + 32',
    description: 'Coolant temperature at the thermostat housing. Drives fuel enrichment and ignition timing maps in the Engine Control Module.',
    decode: tempF,
    format: (v) => `${v} °F`,
    warnHigh: 230,
    critHigh: 240,
  },
  {
    pid: '015C',
    name: 'Engine Oil Temperature',
    shortName: 'Oil Temp',
    category: 'temperature',
    unit: '°F',
    min: -40,
    max: 419,
    formula: '(byte A − 40) × 9 ÷ 5 + 32',
    description: 'Engine oil temperature in the sump. High oil temperature degrades lubrication film strength.',
    decode: tempF,
    format: (v) => `${v} °F`,
    warnHigh: 250,
    critHigh: 270,
  },
  {
    pid: '010F',
    name: 'Intake Air Temperature',
    shortName: 'IAT',
    category: 'temperature',
    unit: '°F',
    min: -40,
    max: 419,
    formula: '(byte A − 40) × 9 ÷ 5 + 32',
    description: 'Air temperature at the Mass Air Flow / Intake Air Temperature sensor. High intake air temperature reduces engine power.',
    decode: tempF,
    format: (v) => `${v} °F`,
  },
  {
    pid: '0146',
    name: 'Ambient Outside Air Temperature',
    shortName: 'Ambient Temp',
    category: 'temperature',
    unit: '°F',
    min: -40,
    max: 419,
    formula: '(byte A − 40) × 9 ÷ 5 + 32',
    description: 'Outside air temperature from the sensor near the front bumper. Used to correct battery state of health estimates.',
    decode: tempF,
    format: (v) => `${v} °F`,
  },

  // ── Fuel ─────────────────────────────────────────────────────────────────────
  {
    pid: '0106',
    name: 'Short-Term Fuel Trim — Bank 1 (Right Side, Cylinders 1,3,5,7)',
    shortName: 'STFT Bank 1',
    category: 'fuel',
    unit: '%',
    min: -100,
    max: 99.2,
    formula: '((byte A − 128) ÷ 128) × 100',
    description: 'Instant Engine Control Module fuel correction for right-side cylinders based on oxygen sensor feedback. Positive = lean (adding fuel).',
    decode: trim,
    format: (v) => { const n = v as number; return `${n > 0 ? '+' : ''}${n}%`; },
    warnLow: -10,
    warnHigh: 10,
    critLow: -25,
    critHigh: 25,
  },
  {
    pid: '0107',
    name: 'Long-Term Fuel Trim — Bank 1 (Right Side, Cylinders 1,3,5,7)',
    shortName: 'LTFT Bank 1',
    category: 'fuel',
    unit: '%',
    min: -100,
    max: 99.2,
    formula: '((byte A − 128) ÷ 128) × 100',
    description: 'Learned persistent fuel correction stored in Engine Control Module memory for Bank 1. High positive value = lean condition.',
    decode: trim,
    format: (v) => { const n = v as number; return `${n > 0 ? '+' : ''}${n}%`; },
    warnLow: -10,
    warnHigh: 10,
    critLow: -25,
    critHigh: 25,
  },
  {
    pid: '0108',
    name: 'Short-Term Fuel Trim — Bank 2 (Left Side, Cylinders 2,4,6,8)',
    shortName: 'STFT Bank 2',
    category: 'fuel',
    unit: '%',
    min: -100,
    max: 99.2,
    formula: '((byte A − 128) ÷ 128) × 100',
    description: 'Instant fuel correction for left-side cylinders. Both banks lean simultaneously points to an upstream cause.',
    decode: trim,
    format: (v) => { const n = v as number; return `${n > 0 ? '+' : ''}${n}%`; },
    warnLow: -10,
    warnHigh: 10,
  },
  {
    pid: '0109',
    name: 'Long-Term Fuel Trim — Bank 2 (Left Side, Cylinders 2,4,6,8)',
    shortName: 'LTFT Bank 2',
    category: 'fuel',
    unit: '%',
    min: -100,
    max: 99.2,
    formula: '((byte A − 128) ÷ 128) × 100',
    description: 'Learned correction for Bank 2. Both banks above +7% signals a global lean condition.',
    decode: trim,
    format: (v) => { const n = v as number; return `${n > 0 ? '+' : ''}${n}%`; },
    warnLow: -10,
    warnHigh: 10,
  },
  {
    pid: '012F',
    name: 'Fuel Tank Level Remaining',
    shortName: 'Fuel Level',
    category: 'fuel',
    unit: '%',
    min: 0,
    max: 100,
    formula: '(byte A ÷ 255) × 100',
    description: 'Fuel level sensor signal from the sender float in the fuel tank.',
    decode: pct1,
    format: (v) => `${v}%`,
    warnLow: 15,
    critLow: 5,
  },
  {
    pid: '0123',
    name: 'Fuel Rail Gauge Pressure',
    shortName: 'Fuel Rail PSI',
    category: 'fuel',
    unit: 'psi',
    min: 0,
    max: 1160,
    formula: '((byte A × 256) + byte B) × 10 kPa → × 0.14504 for psi',
    description: 'Fuel rail pressure above atmospheric. The 5.3 L Vortec uses a returnless rail controlled by the Engine Control Module. Spec: 55–60 psi.',
    decode: (b) => parseFloat(((b[0] * 256 + b[1]) * 10 * 0.14504).toFixed(1)),
    format: (v) => `${v} psi`,
    warnLow: 50,
    warnHigh: 65,
  },
  {
    pid: '015E',
    name: 'Engine Fuel Consumption Rate',
    shortName: 'Fuel Rate',
    category: 'fuel',
    unit: 'L/h',
    min: 0,
    max: 3276.75,
    formula: '((byte A × 256) + byte B) ÷ 20',
    description: 'Instantaneous fuel flow rate calculated from injector duty cycle.',
    decode: lph,
    format: (v) => `${v} L/h`,
  },
  {
    pid: '015D',
    name: 'Fuel Injection Timing — Commanded Angle',
    shortName: 'Inj Timing',
    category: 'fuel',
    unit: '°',
    min: -210,
    max: 301.99,
    formula: '((byte A × 256) + byte B) ÷ 128 − 210',
    description: 'Angle at which fuel injection begins relative to top dead center. Advanced at higher load.',
    decode: (b) => parseFloat(((b[0] * 256 + b[1]) / 128 - 210).toFixed(2)),
    format: (v) => `${v}°`,
  },
  {
    pid: '012A',
    name: 'Fuel System Status — Bank 1 (Closed or Open Loop)',
    shortName: 'Fuel Sys B1',
    category: 'fuel',
    unit: '',
    min: 0,
    max: 255,
    formula: 'Bit-coded status byte',
    description: 'Whether the Engine Control Module is using oxygen sensor feedback (closed loop = normal) or a fixed fuel map (open loop = startup or fault).',
    decode: (b) => b[0],
    format: (v) => {
      const map: { [k: number]: string } = { 1: 'Open loop', 2: 'Closed loop', 4: 'Open loop — fault', 8: 'Closed loop — fault' };
      return map[v as number] ?? `Status ${v}`;
    },
  },

  // ── Electrical ───────────────────────────────────────────────────────────────
  {
    pid: '0142',
    name: 'Engine Control Module Supply Rail Voltage',
    shortName: 'ECM Voltage',
    category: 'electrical',
    unit: 'V',
    min: 0,
    max: 65.535,
    formula: '((byte A × 256) + byte B) ÷ 1000',
    description: 'Battery voltage at the Engine Control Module reference pin. Compare to adapter reading to check wiring resistance drop.',
    decode: volt1,
    format: (v) => `${v} V`,
    warnLow: 11.5,
    critLow: 11.0,
  },
  {
    pid: '0133',
    name: 'Barometric Pressure (Atmospheric)',
    shortName: 'Baro Pressure',
    category: 'electrical',
    unit: 'inHg',
    min: 0,
    max: 36.75,
    formula: 'byte A × 0.29530 (kilopascal to inches of mercury)',
    description: 'Atmospheric pressure used to compensate Mass Air Flow and altitude-sensitive fuel calculations.',
    decode: (b) => parseFloat((b[0] * 0.29530).toFixed(2)),
    format: (v) => `${v} inHg`,
  },
  {
    pid: '0143',
    name: 'Absolute Throttle Body Air Intake Load Value',
    shortName: 'Abs Load',
    category: 'electrical',
    unit: '%',
    min: 0,
    max: 100,
    formula: '((byte A × 256) + byte B) ÷ 2.55',
    description: 'Absolute percentage of maximum possible air intake at current conditions.',
    decode: pct2,
    format: (v) => `${v}%`,
  },

  // ── Oxygen Sensors ───────────────────────────────────────────────────────────
  {
    pid: '0114',
    name: 'Oxygen Sensor Voltage — Bank 1, Upstream (Pre-Catalytic Converter)',
    shortName: 'O2 B1S1',
    category: 'oxygen_sensors',
    unit: 'V',
    min: 0,
    max: 1.275,
    formula: 'byte A ÷ 200',
    description: 'Upstream oxygen sensor on Bank 1, before the catalytic converter. Should oscillate rapidly between 0.1–0.9 V in closed-loop fuel control.',
    decode: o2v,
    format: (v) => `${v} V`,
  },
  {
    pid: '0115',
    name: 'Oxygen Sensor Voltage — Bank 1, Downstream (Post-Catalytic Converter)',
    shortName: 'O2 B1S2',
    category: 'oxygen_sensors',
    unit: 'V',
    min: 0,
    max: 1.275,
    formula: 'byte A ÷ 200',
    description: 'Downstream catalytic converter monitor sensor on Bank 1. A steady reading around 0.65 V indicates a healthy catalytic converter.',
    decode: o2v,
    format: (v) => `${v} V`,
  },
  {
    pid: '0118',
    name: 'Oxygen Sensor Voltage — Bank 2, Upstream (Pre-Catalytic Converter)',
    shortName: 'O2 B2S1',
    category: 'oxygen_sensors',
    unit: 'V',
    min: 0,
    max: 1.275,
    formula: 'byte A ÷ 200',
    description: 'Upstream oxygen sensor on Bank 2 (driver side). Should oscillate rapidly in closed-loop fuel control.',
    decode: o2v,
    format: (v) => `${v} V`,
  },
  {
    pid: '0119',
    name: 'Oxygen Sensor Voltage — Bank 2, Downstream (Post-Catalytic Converter)',
    shortName: 'O2 B2S2',
    category: 'oxygen_sensors',
    unit: 'V',
    min: 0,
    max: 1.275,
    formula: 'byte A ÷ 200',
    description: 'Post-catalytic converter sensor on Bank 2. Steady reading indicates catalyst is functioning correctly.',
    decode: o2v,
    format: (v) => `${v} V`,
  },

  // ── Transmission ─────────────────────────────────────────────────────────────
  {
    pid: '01A4',
    name: 'Transmission Actual Gear — GM Enhanced Parameter',
    shortName: 'Gear',
    category: 'transmission',
    unit: '',
    min: 0,
    max: 7,
    formula: 'Enumerated byte via GM Class II bus',
    description: 'Current gear as reported by the Transmission Control Module via the GM Class II bus. Requires OBDLink MX+ SW-CAN passthrough.',
    decode: (b) => b[0],
    format: (v) => ['Park', 'Reverse', 'Neutral', '1st', '2nd', '3rd', '4th'][v as number] ?? `Gear ${v}`,
  },

  // ── Emissions ────────────────────────────────────────────────────────────────
  {
    pid: '012C',
    name: 'Exhaust Gas Recirculation Valve — Commanded Position',
    shortName: 'EGR Cmd',
    category: 'emissions',
    unit: '%',
    min: 0,
    max: 100,
    formula: '(byte A ÷ 255) × 100',
    description: 'Exhaust Gas Recirculation valve position commanded by the Engine Control Module to reduce nitrogen oxide emissions. 0% at idle is normal.',
    decode: pct1,
    format: (v) => `${v}%`,
  },
  {
    pid: '012D',
    name: 'Exhaust Gas Recirculation Error — Actual vs Commanded Deviation',
    shortName: 'EGR Error',
    category: 'emissions',
    unit: '%',
    min: -100,
    max: 99.2,
    formula: '((byte A − 128) ÷ 128) × 100',
    description: 'Deviation between the commanded and actual Exhaust Gas Recirculation valve position. High error suggests a stuck or leaking valve.',
    decode: trim,
    format: (v) => { const n = v as number; return `${n > 0 ? '+' : ''}${n}%`; },
    warnLow: -15,
    warnHigh: 15,
  },
  {
    pid: '012E',
    name: 'Evaporative Emission Control Purge Valve Duty Cycle',
    shortName: 'EVAP Purge',
    category: 'emissions',
    unit: '%',
    min: 0,
    max: 100,
    formula: '(byte A ÷ 255) × 100',
    description: 'Evaporative Emission Control canister purge valve duty cycle. If stuck open at idle it introduces excess fuel vapour causing a lean condition.',
    decode: pct1,
    format: (v) => `${v}%`,
  },
];

// ─── Lookup by PID string ──────────────────────────────────────────────────────

export const PID_MAP: Map<string, PIDDefinition> = new Map(
  PID_CATALOG.map((p) => [p.pid, p])
);

// ─── Default polling priority queue ───────────────────────────────────────────
// Fast (100 ms): safety-critical
// Normal (500 ms): standard telemetry
// Slow (2000 ms): background

export const POLLING_FAST   = ['010C', '0142'];  // battery voltage (ATRV) is polled separately every cycle
export const POLLING_NORMAL = ['010D', '0105', '0104', '0111', '010F', '0110', '010B', '0106', '0107', '0108', '0109', '0114', '0115', '0118', '0119'];
export const POLLING_SLOW   = ['012F', '015C', '0123', '015E', '0133', '010E', '0143', '012C', '012D', '012E', '01A4'];
